proyecto/abdpro/abdpro/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.languageInfo.urls')),
    re_path('', include('applications.country.urls')),
    re_path('', include('applications.city.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/abdpro/applications/country/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "country_app"

urlpatterns = [
        path('NewCountry/',
                views.NewCountry.as_view(),
                name='NewCountry'),
        path('CountryAPISerializer/',
                views.CountryAPISerializer.as_view(),
                name='CountryAPISerializer'),
]

proyecto/abdpro/applications/inicio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "inicio_app"

urlpatterns = [
    path('InicioTemplateView',
         views.InicioTemplateView.as_view(),
         name='InicioTemplateView'),
]

proyecto/abdpro/applications/country/models.py
from django.db import models

class Country(models.Model):
    code = models.CharField(
        'code',
        null=False,
        max_length=7
    )
    
    name = models.CharField(
        'Name',
        null=False,
        max_length=50,
        unique=True
    )
    
    continent = models.CharField(
        'Continent',
        null=False,
        default='Asia'
    )
    
    region = models.CharField(
        'Region',
        null=False,
        max_length=26,
        default=''
    )
    
    surface_area = models.DecimalField(
        'SurfaceArea',
        null=False,
        max_digits=10,
        decimal_places=2,
        default=0.0
    )
    
    independence = models.SmallIntegerField(
        'IndepYear',
        null=False,
    )
    
    population = models.BigIntegerField(
        'Population',
        null=False,
        default=0
    )
    
    life_expectancy = models.DecimalField(
        'LifeExpectancy',
        null=False,
        max_digits=3,
        decimal_places=1,
        default=0.0
    )
    
    gnp = models.DecimalField(
        'GNP',
        null=True,
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    
    gnp_old = models.DecimalField(
        'GNPOld',
        null=True,
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    
    local_name = models.CharField(
        'LocalName',
        null=False,
        default='',
        max_length=50
    )
    
    government_form = models.CharField(
        'GovernmentForm',
        max_length=50,
        default=''
    )
    
    head_of_state = models.CharField(
        'HeadOfState',
        max_length=60,
        default=''
    )
    
    capital = models.IntegerField(
        'Capital',
        default=0
    )
    
    arable_land_area = models.DecimalField(
        'ArableLandArea',
        null=False,
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    
    hdi = models.DecimalField(
        'HDI',
        max_digits=5,
        decimal_places=3,
        default=0.0
    )
    
    national_currency = models.CharField(
        'NationalCurrency',
        null=False,
        max_length=4,
        default=''
    )
    
    search_fields = ('name', 'code',)
    list_filter = ('name',)
    
    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'
        ordering = ['name']
        unique_together = ('name', 'code')
    
    def __str__(self):
        return f"{self.name} - {self.code} - {self.id}"

proyecto/abdpro/applications/country/forms.py
# ------------------------------------------------------------------
# DJANGO
# ------------------------------------------------------------------

from django import forms

# ------------------------------------------------------------------
# MODELO
# ------------------------------------------------------------------

from .models import Country

# ------------------------------------------------------------------
# FORMULARIO
# ------------------------------------------------------------------
class NewCountryForm(forms.ModelForm):
    """Form definition for Country."""
    class Meta:
        """Meta definition for Countryform."""
        # Modelo al que se aplica el formulario
        model = Country
        # Campos usados en el formulario
        fields = (
            'code',
            'name',
            'continent',
            'region',
            'surface_area',
            'independence',
            'population',
            'life_expectancy',
            'gnp',
            'gnp_old',
            'local_name',
            'government_form',
            'head_of_state',
            'capital',
            'arable_land_area',
            'hdi',
            'national_currency',
        )
        # Labels de los campos del formulario
        labels = {
            'code': 'CodigoCountry',
            'name': 'NombreCountry',
            'continent': 'Continente',
            'region': 'Region',
            'surface_area': 'Superficie',
            'independence': 'DiaIndependencia',
            'population': 'Poblacion',
            'life_expectancy': 'EsperanzaVida',
            'gnp': 'ProductoBruto',
            'gnp_old': 'ProductoBrutoAnterior',
            'local_name': 'NombreLocal',
            'government_form': 'FormaGobierno',
            'head_of_state': 'JefeEstado',
            'capital': 'Capital',
            'arable_land_area': 'TierraCultivable',
            'hdi': 'HDI',
            'national_currency': 'MonedaNacional',
        }
                # Espacio para agregar características a los campos
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'ContainerCityFormSelect',
                        'placeholder':'Nombre de Pais'}
            ),
            'continent': forms.TextInput(
                attrs={
                    'class': 'ContainerCityFormName',
                    'placeholder': 'Distrito'
                }
            ),
            'region': forms.TextInput(
                attrs={
                    'class': 'ContainerCityFormName',
                    'placeholder': 'Poblacion'
                }
            ),
            'surface_area': forms.TextInput(
                attrs={
                    'class': 'ContainerCityFormName',
                    'placeholder': 'Indice de Seguridad '
                }
            ),
            'independence': forms.TextInput(
                attrs={
                    'class': 'ContainerCityFormName',
                    'placeholder': 'Indice de contaminacion'
                }
            ),
        }

proyecto/abdpro/applications/country/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
# Create your views here.

# ------------------------------------------------------------------
# APIS
# ------------------------------------------------------------------
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    # DetailView
    RetrieveAPIView,
    # Delete
    DestroyAPIView,
    # Actualizar
    UpdateAPIView,
    # Recupera y actualiza
    RetrieveUpdateAPIView,
    # Recupera y elimina
    RetrieveDestroyAPIView,
)

from .serializer import (
    CountrySerializer
)
# ------------------------------------------------------------------
# VISTAS A USAR
# ------------------------------------------------------------------

from django.views.generic import ListView, CreateView, UpdateView, DeleteView

# ------------------------------------------------------------------
# MODELOS
# ------------------------------------------------------------------
from .models import Country

# ------------------------------------------------------------------
# FORMULARIOS
# ------------------------------------------------------------------

from .forms import NewCountryForm

# ------------------------------------------------------------------
# CREAR Country
# ------------------------------------------------------------------

class NewCountry(CreateView):
    # Modelo usado para la vista
    model = Country
    # Template usado en la vista
    template_name = 'Country/NewCountry.html'
    # Contexto usado para la impresión en el html
    context_object_name = 'NewCountry'
    # formulario usado en la vista
    form_class = NewCountryForm
    # Dirección a la que va cuando se ejecuta el submit
    success_url = reverse_lazy('inicio_app:home')

    def form_valid(self, form):
        # Guardando los datos del formulario
        country = form.save(commit=False)
        country.save()
        # Return del formulario completado
        return super(NewCountry, self).form_valid(form)

# ------------------------------------------------------------------
# API CREAR UN TRABAJO
# ------------------------------------------------------------------
class CountryAPISerializer(CreateAPIView):
    serializer_class = CountrySerializer

proyecto/abdpro/templates/Country/NewCountry.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Inicio bloque título-->
{%block tittle %} Crear Pais {% endblock tittle %}
<!-- Fin bloque título-->
{% block body %}
<!-- inicio nav -->
{% include 'base/menu.html' %}
<div class="Container">
  <div class="ContainerPais">
    <h1 class="ContainerPaisTitulo m-3">Agregar Pais</h1>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Codigo: {{form.code}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Nombre del pais: {{form.name}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Continente: {{form.continent}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Region: {{form.region}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Superficie: {{form.surface_area}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Dia independencia: {{form.independence}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Poblacion: {{form.population}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Esperanza de Vida: {{form.life_expectancy}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Producto Bruto: {{form.gnp}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Producto Bruto Anterior: {{form.gnp_old}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Nombre local: {{form.local_name}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Forma de Gobierno: {{form.government_form}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Jefe de estado: {{form.head_of_state}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Capital: {{form.capital}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Area cultivable: {{form.arable_land_area}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        HDI: {{form.hdi}}
      </div>
      <div class="ContainerPaisFieldsField m-3">
        <!-- Nombre del departamento-->
        Moneda nacional: {{form.national_currency}}
      </div>
      <button type="submit" class="btn btn-primary m-3 btn-lg">Guardar</button>
    </form>
    <a
      class="btn btn-outline-secondary"
      href="{% url 'inicio_app:InicioTemplateView' %}"
    >
      Volver
    </a>
  </div>
</div>
{% include 'base/footer.html' %} {% endblock body %}